dist: xenial    # required for Python >= 3.7
language: python
sudo: false

python:
  - "3.5"

env:
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=py37
  - TOXENV=py36-black

install:
  - pip install -r requirements-test.txt

script:
  - tox -v -e py