"""Added LogRow.

Revision ID: 46b2aa123b90
Revises: a9078456e117
Create Date: 2020-01-30 21:03:45.953310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46b2aa123b90'
down_revision = 'a9078456e117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_row_sensor_id'), 'log_row', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_row_sensor_id'), table_name='log_row')
    op.drop_table('log_row')
    # ### end Alembic commands ###
