"""Added firmware version for sensors.

Revision ID: 47775f7e7c00
Revises: 46b2aa123b90
Create Date: 2020-05-01 14:35:54.681256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47775f7e7c00'
down_revision = '46b2aa123b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('firmware_version', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'firmware_version')
    # ### end Alembic commands ###
